name: CI Build

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'    
  workflow_call:
    outputs:
      version:
        description: "Version"
        value: ${{ jobs.build.outputs.version }}
      version_MajorMinorPatch:
        description: "Version (without prerelease tag)"
        value: ${{ jobs.build.outputs.version_MajorMinorPatch }}

jobs:
  test:
    name: Test
    runs-on: windows-2019
    permissions:
      id-token: write
      contents: read
      checks: write    
    steps:
    - uses: actions/setup-dotnet@latest
      with:
        dotnet-version: '7.0.x'
        include-prerelease: true 
    - uses: actions/checkout@latest
      with: 
        fetch-depth: 0    
    - name: Run Tests
      id: tests
      run: ./build/02-test.ps1
    - name: Test Report DotNet
      uses: dorny/test-reporter@latest
      if: success() || failure()
      with:
        name: TestsResults (dotnet)
        path: "**/TestResults*.trx"                            
        reporter: dotnet-trx
        fail-on-error: true
    - name: Test Report PowerShell v5
      uses: dorny/test-reporter@latest
      if: success() || failure()
      with:
        name: TestsResults (PowerShell v5)
        path: ./testResults_PS5.xml
        reporter: java-junit
        fail-on-error: true
    - name: Test Report PowerShell v7
      uses: dorny/test-reporter@latest
      if: success() || failure()
      with:
        name: TestsResults (PowerShell v7)
        path: ./testResults_PS7.xml
        reporter: java-junit
        fail-on-error: true
  build:
    name: Build
    runs-on: windows-latest
    steps:
    - uses: actions/setup-dotnet@latest
      with:
        dotnet-version: '7.0.x'
        include-prerelease: true 
    - uses: actions/checkout@latest
      with: 
        fetch-depth: 0
    - name: Install dependencies
      run: choco install GitVersion.Portable ilmerge --confirm --no-progress
    - name: Update project version
      run: gitversion /l console /output buildserver /updateAssemblyInfo /verbosity minimal
    - name: Get project version
      id: getversion
      run: |
           echo "version=$(gitversion /showvariable LegacySemVer)" >> $GITHUB_OUTPUT
           echo "version_MajorMinorPatch=$(gitversion /showvariable MajorMinorPatch)" >> $GITHUB_OUTPUT
    - name: Build
      run: ./build/01-build.ps1
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Binaries
        path: ./artifacts
    outputs:
      version:                 ${{ steps.getversion.outputs.version }}
      version_MajorMinorPatch: ${{ steps.getversion.outputs.version_MajorMinorPatch }}
